<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <relativePath>qct</relativePath>
        <groupId>com.github.aleksikangas</groupId>
        <artifactId>qct</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>qct-convert</artifactId>
    <packaging>pom</packaging>

    <developers>
        <developer>
            <id>aleksi-kangas</id>
            <name>Aleksi Kangas</name>
            <email>aleksi.kangas@hotmail.com</email>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/license/mit</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://github.com/aleksi-kangas/qct-convert.git</connection>
        <developerConnection>scm:git:git@github.com:aleksi-kangas/qct-convert.git</developerConnection>
        <url>https://github.com/aleksi-kangas/qct-convert</url>
    </scm>

    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/aleksi-kangas/qct-convert/issues</url>
    </issueManagement>

    <ciManagement>
        <system>GitHub Actions</system>
        <url>https://github.com/aleksi-kangas/qct-convert/actions</url>
    </ciManagement>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>central</id>
            <name>Maven Central Repository</name>
            <url>https://repo1.maven.org/maven2/</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>imageio-ext-repository</id>
            <name>imageio-ext Repository</name>
            <url>https://maven.geo-solutions.it/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <modules>
        <module>qct</module>
        <module>qct-core</module>
        <module>qct-export</module>
        <module>qct-ui</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors>
                        <descriptor>qct/assembly/release.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.github.aleksikangas</groupId>
            <artifactId>qct-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.aleksikangas</groupId>
            <artifactId>qct-export</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.aleksikangas</groupId>
            <artifactId>qct-ui</artifactId>
        </dependency>
    </dependencies>
</project>