name: Build

on:
  push:
    branches: [ "master", "java" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "master", "java" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest,windows-latest ]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Install JDK"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"

      - name: "Install Conda"
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: gdal
          auto-activate-base: false
          auto-update-conda: true
          environment-file: ${{ github.workspace }}/gdal/conda-environment.yaml

      - name: "Build GDAL with Java bindings"
        working-directory: ${{ github.workspace }}/gdal
        shell: bash -l {0}
        run: |
          chmod +x ./gdal-build.sh
          ./gdal-build.sh

      - name: "Copy GDAL libraries"
        working-directory: ${{ github.workspace }}/gdal
        shell: bash -l {0}
        run: |
          chmod +x ./copy-libraries.sh
          ./copy-libraries.sh

      - name: "Package"
        run: mvn -B clean package

      - name: "Upload artifact"
        uses: actions/upload-artifact@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ matrix.os }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/target/*.zip

  release:
    name: "Create GitHub Release"
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v6
        with:
          path: ./artifacts

      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            artifacts/**/**/*.zip
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}